# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('item_pic', models.URLField(default='#')),
                ('item_price', models.PositiveIntegerField(default=0)),
                ('item_num', models.PositiveIntegerField(default=0)),
                ('item_des', models.TextField(default='\u6682\u65e0\u8bf4\u660e')),
            ],
        ),
    ]
