# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
